import { VerticalBox, Button, Palette } from "std-widgets.slint";

export component App inherits Window {
    in property <image> video-frame <=> image.source;
    in property <bool> playing;

    pure callback toggle-pause-play();
    callback open-file;

    preferred-width: 500px;
    preferred-height: 500px;
    min-width: 500px;
    min-height: 300px;
    title: "Slint FFMPEG Example";
    background: #000000;

    states [
        shown when area.has-hover || animation-tick() < 5s : {
            controls.opacity: 1;
            in {
                animate controls.opacity {
                    duration: 50ms;
                }
            }
        }
        hidden when !area.has-hover: {
            controls.opacity: 0;
            in {
                animate controls.opacity {
                    delay: 3s;
                    duration: 500ms;
                }
            }
        }
    ]

    VerticalBox {
        Button {
            height: 50px;
            text: "Open";
            clicked => {
                root.open-file();
            }
        }
        image := Image {
            min-height: 300px;
        }
    }

    area := TouchArea {
        width: 100%;
        height: self.preferred-height;
        y: root.height - self.height - 40px;
        controls := Rectangle {
            border-radius: 4px;
            background: Palette.color-scheme == ColorScheme.dark ? #3737378c : #ffffff82;

            Image {
                width: 64px;
                height: 64px;
                source: root.playing ? @image-url("../icons/pause.svg") : @image-url("../icons/play.svg");
            }

            TouchArea {
                clicked => {
                    root.toggle-pause-play();
                }
            }
        }
    }
}
